import grpc

class Manager:
    def __init__(self, ch: grpc.Channel) -> None: ...
    def List(self) -> list[str]: ...
    def Health(self) -> str: ...
    def Install(self, name): ...
    def Uninstall(self, name): ...
    def Env(self, name: str) -> list[str]: ...
    def Exe(self, name: str) -> str: ...
    def Args(self, name: str) -> list[str]: ...
    def Files(self, name: str) -> list[str]: ...
