import io
from typing import Generator

import grpc

class Shell:
    def __init__(self, ch: grpc.Channel): ...
    def Run(self, command: str, timeout: int = 0) -> bytes: ...
    def Push(self, file: io.BufferedReader, filname: str): ...
    def Pull(self, filename: str) -> Generator[bytes, None, None]: ...
    def Install(self, apkpath: str): ...
    def Uninstall(self, pkgname: str): ...
    def ListApps(self) -> list[str]: ...
    def StartApp(self, activity: str): ...
    def StopApp(self, pkgname: str): ...
    def Getprop(self, key: str) -> str: ...
