import grpc

from .protos import window

class Window:
    stub: window.WindowStub

    def __init__(self, ch: grpc.Channel): ...
    def GetSize(self) -> tuple[int, int]: ...
    def SetSize(self, width: int, height: int): ...
    def GetDensity(self) -> int: ...
    def SetDensity(self, density: int): ...
    def ResetSize(self): ...
    def ResetDensity(self): ...
    def SetRotation(self, lock: bool, rotation: int): ...
