name: Publish PyPI and TestPyPI
on: push
jobs:
    build-and-publish:
        name: Build and publish
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install pypa/build
              run: >-
                  python -m pip install build --user

            - name: Install grpcio-tools
              run: >-
                  python -m pip install grpcio-tools --user

            - name: Generate protos
              run: >-
                  python ./gen_protos.py

            - name: Build a binary wheel and a source tarball
              run: >-
                  python -m build --sdist --wheel --outdir dist/ .

            - name: Publish distribution 📦 to Test PyPI
              continue-on-error: true
              uses: pypa/gh-action-pypi-publish@release/v1.8
              with:
                  repository-url: https://test.pypi.org/legacy/

            - name: Publish distribution 📦 to PyPI
              if: startsWith(github.ref, 'refs/tags')
              continue-on-error: true
              uses: pypa/gh-action-pypi-publish@release/v1.8
